/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_clients__client_id__get"];
        /** Update Client */
        put: operations["update_client_api_clients__client_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}/disattiva": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Client */
        post: operations["deactivate_client_api_clients__client_id__disattiva_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/veterinarians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Veterinarians */
        get: operations["list_veterinarians_api_veterinarians_get"];
        put?: never;
        /** Create Veterinarian */
        post: operations["create_veterinarian_api_veterinarians_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/veterinarians/{veterinarian_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Veterinarian */
        get: operations["get_veterinarian_api_veterinarians__veterinarian_id__get"];
        /** Update Veterinarian */
        put: operations["update_veterinarian_api_veterinarians__veterinarian_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/veterinarians/{veterinarian_id}/disattiva": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Veterinarian */
        post: operations["deactivate_veterinarian_api_veterinarians__veterinarian_id__disattiva_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClientCreate */
        ClientCreate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Phone 2 */
            phone_2?: string | null;
            /** Email */
            email?: string | null;
            /** Tax Code */
            tax_code?: string | null;
            /** Vat Number */
            vat_number?: string | null;
            /** Street */
            street?: string | null;
            /** City */
            city?: string | null;
            /** Province */
            province?: string | null;
            /** Zip */
            zip?: string | null;
            /** Address */
            address?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ClientRead */
        ClientRead: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Company Name */
            company_name: string | null;
            /** Phone */
            phone: string | null;
            /** Phone 2 */
            phone_2: string | null;
            /** Email */
            email: string | null;
            /** Tax Code */
            tax_code: string | null;
            /** Vat Number */
            vat_number: string | null;
            /** Street */
            street: string | null;
            /** City */
            city: string | null;
            /** Province */
            province: string | null;
            /** Zip */
            zip: string | null;
            /** Address */
            address: string | null;
            /** Notes */
            notes: string | null;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Phone 2 */
            phone_2?: string | null;
            /** Email */
            email?: string | null;
            /** Tax Code */
            tax_code?: string | null;
            /** Vat Number */
            vat_number?: string | null;
            /** Street */
            street?: string | null;
            /** City */
            city?: string | null;
            /** Province */
            province?: string | null;
            /** Zip */
            zip?: string | null;
            /** Address */
            address?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "operator";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VeterinarianCreate */
        VeterinarianCreate: {
            /** Clinic Name */
            clinic_name?: string | null;
            /** Doctor Name */
            doctor_name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Notes */
            notes?: string | null;
            /** Service Duration Minutes */
            service_duration_minutes?: number | null;
            /** Hours */
            hours?: components["schemas"]["VeterinarianHoursInput"][];
        };
        /** VeterinarianHoursInput */
        VeterinarianHoursInput: {
            /** Day Of Week */
            day_of_week: number;
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Morning Start */
            morning_start?: string | null;
            /** Morning End */
            morning_end?: string | null;
            /** Afternoon Start */
            afternoon_start?: string | null;
            /** Afternoon End */
            afternoon_end?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** VeterinarianHoursRead */
        VeterinarianHoursRead: {
            /** Day Of Week */
            day_of_week: number;
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Morning Start */
            morning_start?: string | null;
            /** Morning End */
            morning_end?: string | null;
            /** Afternoon Start */
            afternoon_start?: string | null;
            /** Afternoon End */
            afternoon_end?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
        };
        /** VeterinarianRead */
        VeterinarianRead: {
            /** Id */
            id: number;
            /** Clinic Name */
            clinic_name: string | null;
            /** Doctor Name */
            doctor_name: string | null;
            /** Short Name */
            short_name: string | null;
            /** Phone */
            phone: string | null;
            /** Address */
            address: string | null;
            /** City */
            city: string | null;
            /** Notes */
            notes: string | null;
            /** Active */
            active: boolean;
            /** Service Duration Minutes */
            service_duration_minutes: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Hours */
            hours: components["schemas"]["VeterinarianHoursRead"][];
        };
        /** VeterinarianUpdate */
        VeterinarianUpdate: {
            /** Clinic Name */
            clinic_name?: string | null;
            /** Doctor Name */
            doctor_name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Notes */
            notes?: string | null;
            /** Service Duration Minutes */
            service_duration_minutes?: number | null;
            /** Hours */
            hours?: components["schemas"]["VeterinarianHoursInput"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_clients_get: {
        parameters: {
            query?: {
                /** @description Ricerca per nome, ragione sociale, telefono o email */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_clients__client_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_client_api_clients__client_id__disattiva_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_veterinarians_api_veterinarians_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VeterinarianRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_veterinarian_api_veterinarians_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VeterinarianCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VeterinarianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_veterinarian_api_veterinarians__veterinarian_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                veterinarian_id: number;
            };
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VeterinarianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_veterinarian_api_veterinarians__veterinarian_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                veterinarian_id: number;
            };
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VeterinarianUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VeterinarianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_veterinarian_api_veterinarians__veterinarian_id__disattiva_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                veterinarian_id: number;
            };
            cookie?: {
                ppm_v2_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VeterinarianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
