"""release hardening - login attempts rate limit

Revision ID: 2d60265bb09c
Revises: aadb1ea5e32e
Create Date: 2026-08-27 09:00:54.282290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d60265bb09c'
down_revision = 'aadb1ea5e32e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username_key', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_username_key'), 'login_attempts', ['username_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_attempts_username_key'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
