"""dominio pratiche - modello dati completo

Revision ID: 7598b50714a9
Revises: 0cb1ed9974e6
Create Date: 2026-08-26 17:59:05.299996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7598b50714a9'
down_revision = '0cb1ed9974e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('has_cremation_plant', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('practice_number_counters',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('urns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ritirato', 'in_programma', 'cremato', 'da_consegnare', 'consegnato', 'smaltito', name='practice_status'), nullable=False),
    sa.Column('request_origin', sa.String(length=30), nullable=False),
    sa.Column('originating_pickup_event_id', sa.Integer(), nullable=True),
    sa.Column('destination_branch_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=True),
    sa.Column('veterinarian_id', sa.Integer(), nullable=True),
    sa.Column('origin_veterinarian_id', sa.Integer(), nullable=True),
    sa.Column('cremation_cycle_id', sa.Integer(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('pickup_time', sa.Time(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('microchip', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ddt_number', sa.Integer(), nullable=True),
    sa.Column('ddt_date', sa.Date(), nullable=True),
    sa.Column('ddt_pdf_path', sa.Text(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('data_complete', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('owner_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transport_method', sa.String(length=100), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('temperature_mode', sa.String(length=60), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('treatment_method', sa.String(length=100), nullable=True),
    sa.Column('delivery_at_clinic', sa.Boolean(), nullable=False),
    sa.Column('delivery_at_home', sa.Boolean(), nullable=False),
    sa.Column('signatory_identity_document_number', sa.String(length=60), nullable=True),
    sa.Column('signatory_identity_document_date', sa.Date(), nullable=True),
    sa.Column('signatory_signing_place', sa.String(length=120), nullable=True),
    sa.Column('ddt_share_token', sa.String(length=64), nullable=True),
    sa.Column('original_practice_number', sa.String(length=32), nullable=True),
    sa.Column('pickup_type', sa.Enum('sede_aziendale', 'domicilio', 'veterinario', 'collaboratore', 'altro', name='pickup_type'), nullable=False),
    sa.Column('pickup_location_id', sa.Integer(), nullable=True),
    sa.Column('pickup_zone_id', sa.Integer(), nullable=True),
    sa.Column('pickup_contact_name', sa.String(length=160), nullable=True),
    sa.Column('provenance_code', sa.String(length=30), nullable=True),
    sa.Column('computed_total_override_cents', sa.BigInteger(), nullable=True),
    sa.Column('computed_total_override_reason', sa.Text(), nullable=True),
    sa.Column('computed_total_override_by', sa.Integer(), nullable=True),
    sa.Column('computed_total_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_invoice', sa.Boolean(), nullable=False),
    sa.Column('send_catalog', sa.Boolean(), nullable=False),
    sa.Column('catalog_sent', sa.Boolean(), nullable=False),
    sa.Column('send_estremi', sa.Boolean(), nullable=False),
    sa.Column('estremi_sent', sa.Boolean(), nullable=False),
    sa.Column('voucher_requested', sa.Boolean(), nullable=False),
    sa.Column('use_voucher', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_thanks_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whatsapp_thanks_last_error', sa.Text(), nullable=True),
    sa.Column('no_whatsapp_message', sa.Boolean(), nullable=False),
    sa.Column('cremation_registered', sa.Boolean(), nullable=False),
    sa.Column('cremation_queued', sa.Boolean(), nullable=False),
    sa.Column('collaborator_billing_status', sa.Enum('da_fatturare', 'fatturato', name='collaborator_billing_status'), nullable=False),
    sa.Column('collaborator_billing_invoiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collaborator_name_fallback', sa.String(length=200), nullable=True),
    sa.Column('owner_notified_status', sa.Enum('da_avvisare', 'avvisato', name='owner_notified_status'), nullable=False),
    sa.Column('owner_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_notified_by', sa.Integer(), nullable=True),
    sa.Column('used_voucher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['computed_total_override_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_branch_id'], ['company_locations.id'], ),
    sa.ForeignKeyConstraint(['origin_veterinarian_id'], ['veterinarians.id'], ),
    sa.ForeignKeyConstraint(['owner_notified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['company_locations.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['calendar_zones.id'], ),
    sa.ForeignKeyConstraint(['veterinarian_id'], ['veterinarians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ddt_number'),
    sa.UniqueConstraint('ddt_share_token'),
    sa.UniqueConstraint('practice_number')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.Integer(), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('species', sa.String(length=60), nullable=True),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('age_years', sa.SmallInteger(), nullable=True),
    sa.Column('age_months', sa.SmallInteger(), nullable=True),
    sa.Column('estimated_weight_grams', sa.Integer(), nullable=True),
    sa.Column('microchip', sa.String(length=60), nullable=True),
    sa.Column('cremation_type', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calendar_event_id IS NOT NULL OR practice_id IS NOT NULL', name='ck_animals_has_owner'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('subtype', sa.String(length=60), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.Enum('W', 'D', 'Collaboratori', name='payment_channel'), nullable=False),
    sa.Column('urn_catalog_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['urn_catalog_id'], ['urns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_tags',
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('practice_id', 'tag_id')
    )
    op.add_column('audit_log', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # doc06 'Convenzioni generali': stesso trigger set_updated_at() gia'
    # creato dalla revisione precedente, applicato alle nuove tabelle che
    # hanno una colonna updated_at.
    for table in ("company_locations", "collaborators", "urns", "practices"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
            """
        )

    # doc06 Addendum C (FACT verificato in app.py, BRANCHES): le due sedi
    # aziendali reali gia' in uso - Livorno (unico impianto di cremazione)
    # ed Empoli.
    op.execute(
        """
        INSERT INTO company_locations (name, has_cremation_plant, active, created_at, updated_at)
        VALUES ('Livorno', true, true, now(), now()), ('Empoli', false, true, now(), now());
        """
    )


def downgrade() -> None:
    for table in ("company_locations", "collaborators", "urns", "practices"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'reason')
    op.drop_table('practice_tags')
    op.drop_table('practice_line_items')
    op.drop_table('animals')
    op.drop_table('practices')
    op.drop_table('urns')
    op.drop_table('tags')
    op.drop_table('practice_number_counters')
    op.drop_table('company_locations')
    op.drop_table('collaborators')
    op.drop_table('calendar_zones')
    # ### end Alembic commands ###
