"""dominio ritiro e riconsegna

Revision ID: 96000ba74899
Revises: 7598b50714a9
Create Date: 2026-08-26 19:57:55.059812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '96000ba74899'
down_revision = '7598b50714a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ritiro', 'riconsegna', name='calendar_event_type'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('veterinarian_id', sa.Integer(), nullable=True),
    sa.Column('collaborator_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_practice_id', sa.Integer(), nullable=True),
    sa.Column('pickup_status', sa.Enum('da_confermare', 'da_ritirare', 'ritirato', 'annullato', name='pickup_status'), nullable=True),
    sa.Column('pickup_type', postgresql.ENUM('sede_aziendale', 'domicilio', 'veterinario', 'collaboratore', 'altro', name='pickup_type', create_type=False), nullable=True),
    sa.Column('pickup_location_id', sa.Integer(), nullable=True),
    sa.Column('pickup_zone_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('pickup_contact_name', sa.Text(), nullable=True),
    sa.Column('delivery_type', sa.Enum('ambulatorio', 'domicilio', 'sede_aziendale', 'altro', name='delivery_type'), nullable=True),
    sa.Column('delivery_veterinarian_id', sa.Integer(), nullable=True),
    sa.Column('delivery_location_id', sa.Integer(), nullable=True),
    sa.Column('delivery_zone_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('preliminary_payment_status', sa.Text(), nullable=True),
    sa.Column('preliminary_payment_amount', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['company_locations.id'], ),
    sa.ForeignKeyConstraint(['delivery_veterinarian_id'], ['veterinarians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['calendar_zones.id'], ),
    sa.ForeignKeyConstraint(['linked_practice_id'], ['practices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['company_locations.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['calendar_zones.id'], ),
    sa.ForeignKeyConstraint(['veterinarian_id'], ['veterinarians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'animals', 'calendar_events', ['calendar_event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'practices', 'calendar_events', ['originating_pickup_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # doc06 'Convenzioni generali': stesso trigger set_updated_at() gia'
    # creato dalla prima migrazione.
    op.execute(
        """
        CREATE TRIGGER trg_calendar_events_set_updated_at
        BEFORE UPDATE ON calendar_events
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_calendar_events_set_updated_at ON calendar_events;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('practices_originating_pickup_event_id_fkey', 'practices', type_='foreignkey')
    op.drop_constraint('animals_calendar_event_id_fkey', 'animals', type_='foreignkey')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
