"""dominio fatture pagamenti

Revision ID: aadb1ea5e32e
Revises: 775a67bfa571
Create Date: 2026-08-27 00:11:57.785195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aadb1ea5e32e'
down_revision = '775a67bfa571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # payment_channel e' gia' stato creato dalla migrazione Pratiche - qui
    # riusato via create_type=False su entrambe le tabelle sotto, stessa
    # correzione gia' necessaria per pickup_type in questa sessione
    # (altrimenti op.create_table tenta comunque una CREATE TYPE duplicata).
    payment_channel_type = postgresql.ENUM('W', 'D', 'Collaboratori', name='payment_channel', create_type=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('total_amount_cents', sa.BIGINT(), nullable=False),
    sa.Column('channel', payment_channel_type, nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('practice_number_snapshot', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('payment_deletions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deletion_kind', sa.String(length=50), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_uuid', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('practice_number_snapshot', sa.String(length=32), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('channel', payment_channel_type, nullable=False),
    sa.Column('ledger_section', sa.Enum('Entrata', 'Uscita', name='ledger_section'), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.BIGINT(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_payment_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=150), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Enum('native', 'v1_migration', 'api', 'automatic', name='payment_source'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('amount_cents <> 0', name='ck_payments_amount_cents_nonzero'),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('payment_uuid')
    )
    op.create_table('invoice_payment_links',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id', 'payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_payment_links')
    op.drop_table('payments')
    op.drop_table('payment_deletions')
    op.drop_table('invoices')
    # ### end Alembic commands ###
