"""release hardening - indici dimostrati su calendar_events e practices

Revision ID: ab009e85b321
Revises: 2d60265bb09c
Create Date: 2026-08-27 09:10:47.411981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab009e85b321'
down_revision = '2d60265bb09c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_calendar_events_active_type_start', 'calendar_events', ['event_type', sa.literal_column('start_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_practices_active_created', 'practices', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_practices_active_status_created', 'practices', ['status', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_practices_active_status_created', table_name='practices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_practices_active_created', table_name='practices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_calendar_events_active_type_start', table_name='calendar_events', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
