"""dominio cicli di cremazione - animal level

Revision ID: c1a3c3b110af
Revises: 96000ba74899
Create Date: 2026-08-26 22:58:55.859111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a3c3b110af'
down_revision = '96000ba74899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cremation_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pianificato', 'in_attesa', 'completato', name='cremation_cycle_status'), nullable=False),
    sa.Column('planned_start', sa.Time(), nullable=False),
    sa.Column('planned_end', sa.Time(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cremation_location_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cremation_location_id'], ['company_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('animals', sa.Column('cremation_cycle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'animals_cremation_cycle_id_fkey', 'animals', 'cremation_cycles', ['cremation_cycle_id'], ['id'], ondelete='SET NULL'
    )
    op.drop_column('practices', 'cremation_cycle_id')
    # ### end Alembic commands ###

    # doc06 'Convenzioni generali': stesso trigger set_updated_at() gia'
    # creato dalla prima migrazione.
    op.execute(
        """
        CREATE TRIGGER trg_cremation_cycles_set_updated_at
        BEFORE UPDATE ON cremation_cycles
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_cremation_cycles_set_updated_at ON cremation_cycles;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('cremation_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('animals_cremation_cycle_id_fkey', 'animals', type_='foreignkey')
    op.drop_column('animals', 'cremation_cycle_id')
    op.drop_table('cremation_cycles')
    # ### end Alembic commands ###
